I create digital instruments and effects, and I believe that software should be available for everyone to use, and for coders to learn from. However, if you are financially able and do wish to support me, here are some sponsorship platforms:

Patreon: http://www.patreon.com/benvining?fan_landing=true
ko-fi: http://www.ko-fi.com/benvining
Gumroad: http://www.gumroad.com/benvining
