name: AutoBuild

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#

jobs:

  build:

    name: ${{ matrix.artifact }} build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
        - os: windows-latest
          artifact: Windows
        - os: ubuntu-latest
          artifact: Linux
        - os: macos-latest
          artifact: MacOS

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: imogen

    - name: Run build script
      shell: bash
      run: bash $GITHUB_WORKSPACE/imogen/imogen_build_script.sh -z
      
    - name: Rename zip file
      shell: bash
      run: cd $GITHUB_WORKSPACE/imogen/Builds && mv Imogen.zip Imogen-${{ matrix.artifact }}.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        path: Builds/Imogen-${{ matrix.artifact }}.zip
        name: Imogen-${{ matrix.artifact }}.zip

#
