name: AutoBuild

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#

jobs:

  build:

    name: ${{ matrix.artifact }} build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
        - os: windows-latest
          artifact: Windows
        - os: ubuntu-latest
          artifact: Linux
        - os: macos-latest
          artifact: MacOS

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: imogen

    - name: Run main build script
      shell: bash
      run: bash $GITHUB_WORKSPACE/imogen/scripts/imogen_build_script.sh
      
    - name: Run iOS build script
      if: matrix.os == 'macos-latest'
      shell: bash
      run: bash $GITHUB_WORKSPACE/imogen/scripts/imogen_build_iOS.sh

#
