name: markdown-link-check

on:
  push:
  workflow_dispatch:

jobs:
 
  link-checker:
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Markdown links check
        uses: ruzickap/action-my-markdown-link-checker@v1
