name: iOS_build

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#

jobs:

  build:

    name: iOS build
    runs-on: macos-latest
    timeout-minutes: 30

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: imogen
 
    - name: Run iOS build script
      shell: bash
      run: bash $GITHUB_WORKSPACE/imogen/scripts/imogen_build_iOS.sh

#
