name: LV2_build

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#

jobs:

  build:

    name: LV2 build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: imogen
 
    - name: Run LV2 build script
      shell: bash
      run: bash $GITHUB_WORKSPACE/imogen/scripts/imogen_build_LV2.sh

#
