name: LV2_build

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#

jobs:

  build:

    name: LV2 build
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    
    - name: Install JUCE's Linux Deps and select g++ 10
      run: |
        sudo apt-get update && sudo apt install libasound2-dev libx11-dev libxinerama-dev libxext-dev libfreetype6-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: imogen
 
    - name: Run LV2 build script
      shell: bash
      run: bash $GITHUB_WORKSPACE/imogen/scripts/imogen_build_LV2.sh

#
