name: Imogen main build

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#

jobs:

  main-build:

    name: ${{ matrix.artifact }} build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
        - os: windows-latest
          artifact: Windows
        - os: ubuntu-latest
          artifact: Linux
        - os: macos-latest
          artifact: MacOS

    steps:
 
    - name: Install JUCE's Linux dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt-get update && sudo apt install libasound2-dev libx11-dev libxinerama-dev libxext-dev libfreetype6-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: imogen

    - name: Run main build script
      shell: bash
      run: bash $GITHUB_WORKSPACE/imogen/scripts/imogen_build_script.sh


  ios-build:
 
     name: iOS build
     runs-on: macos-latest
     timeout-minutes: 30
     
     steps:
     
     - name: Checkout code
       uses: actions/checkout@v2
       with:
        submodules: recursive
        path: imogen
      
     - name: Run iOS build script
       shell: bash
       run: bash $GITHUB_WORKSPACE/imogen/scripts/imogen_build_iOS.sh
       
  plugin-LV2-build:
  
      name: plugin - LV2 build
      runs-on: ubuntu-latest
      timeout-minutes: 30
      
      steps:
      
        - name: Install JUCE's Linux dependencies
          shell: bash
          run: sudo apt-get update && sudo apt install libasound2-dev libx11-dev libxinerama-dev libxext-dev libfreetype6-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev

        - name: Install LV2 development headers
          shell: bash
          run: sudo apt-get install lv2-dev
      
        - name: Checkout code
          uses: actions/checkout@v2
          with:
            submodules: recursive
            path: imogen

        - name: Run main build script
          shell: bash
          run: bash $GITHUB_WORKSPACE/imogen/scripts/imogen_build_script.sh
          
#
