name: Basic repo maintenence & utils

on:
  push:
  schedule:
  - cron: "30 1 * * *"
  workflow_dispatch:

jobs:

#

  link-checker:

    name: Checking for dead links
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Markdown links check
        uses: ruzickap/action-my-markdown-link-checker@v1

#

  stale:

    name: Mark stale pull requests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'

#

  update-submodules:

    name: Updating git submodules
    runs-on: ubuntu-latest

    steps:
      - uses: snickerbockers/submodules-init@v4

#
